# SPDX-FileCopyrightText: 2021 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
contact_links:
    - name: üó∫Ô∏è Feature request for the full Nextcloud Talk suite
      url: https://github.com/nextcloud/spreed/issues/new/choose
      about: Suggest an idea for Nextcloud Talk for all users, client and server
    - name: ‚ùì Community Support and Help
      url: https://help.nextcloud.com/
      about: Configuration, webserver/proxy or performance issues and other questions
